filters:
  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/index.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/index.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/trans.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/trans.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_items_options.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_items_options.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_attribute_table.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_attribute_table.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_legend.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_legend.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_items_shape.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_items_shape.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_scale_bar.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_scale_bar.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_label.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_label.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_html_frame.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_html_frame.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_image.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_image.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_map.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/composer_items/composer_map.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/composer_items/index.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/composer_items/index.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/overview_composer.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/overview_composer.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/create_output.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/create_output.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/print_composer/index.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/print_composer/index.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/working_with_vector/style_library.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/working_with_vector/style_library.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/working_with_vector/vector_properties.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/working_with_vector/vector_properties.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/working_with_vector/editing_geometry_attributes.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/working_with_vector/editing_geometry_attributes.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/working_with_vector/expression.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/working_with_vector/expression.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/working_with_vector/attribute_table.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/working_with_vector/attribute_table.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/working_with_vector/index.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/working_with_vector/index.po

  - filter_type: file
    file_format: PO
    source_language: en
    source_file: source/locale/en/LC_MESSAGES/docs/user_manual/index.po
    translation_files_expression: source/locale/<lang>/LC_MESSAGES/docs/user_manual/index.po

settings:
   language_mapping:
     en: en_US
     nl: nl_NL
     it: it_IT
     de: de_DE
